[project]
name = "cprn"
version = "0.1.0"
description = "CPRN gen app algo"
readme = "README.md"
requires-python = ">=3.11"
dependencies = []

[tool.setuptools.packages.find]
include = ["cprn*"]
exclude = ["jnb*"]